### ISSUE TITLE
Failure to start cluster with couchdb:2.0-dev docker

### ISSUE THREAD

**Issue by peetersn** [klaemo/docker-couchdb#41] opened 2016-01-06 21:26 UTC
I just installed following those guidelines:https://docs.google.com/document/d/1BtndYr-0KDQTqBSLVdJoR_8C5ObYjT1RBo_Qyh5ykdQ/edit#

... and I thought I would report back...

```
docker run -it -p 5984:5984 klaemo/couchdb:2.0-dev
[ * ] Setup environment ... ok
[ * ] Ensure CouchDB is built ... ok
[ * ] Prepare configuration files ... ok
[ * ] Start node node1 ... ok
[ * ] Start node node2 ... ok
[ * ] Start node node3 ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
[ * ] Check node at http://127.0.0.1:25984/ ... ok
[ * ] Check node at http://127.0.0.1:35984/ ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... ok
[ * ] Running cluster setup ... failed: {"error":"bad_request","reason":"Add node failed. Invalid Host and/or Port."}

Traceback (most recent call last):
  File "/usr/src/couchdb/dev/run", line 535, in <module>
    main()
  File "/usr/src/couchdb/dev/run", line 73, in main
    startup(ctx)
  File "/usr/src/couchdb/dev/run", line 307, in startup
    cluster_setup(ctx)
  File "/usr/src/couchdb/dev/run", line 57, in wrapper
    res = func(*args, **kwargs)
  File "/usr/src/couchdb/dev/run", line 397, in cluster_setup
    add_node(lead_port, node_port, *ctx['admin'])
  File "/usr/src/couchdb/dev/run", line 431, in add_node
    assert resp.status in (201, 409), resp.read()
AssertionError: {"error":"bad_request","reason":"Add node failed. Invalid Host and/or Port."}
```

Not sure what to do next...

**Comment by klaemo** [comment] 2016-01-06 21:43
Cannot reproduce :(

did you run `docker pull klaemo/couchdb:2.0-dev` to ensure you have the latest version of the image (in case you had on older one before)?

What's your OS und Docker version?

**Comment by peetersn** [comment] 2016-01-06 21:46
I just installed Docker a few minutes ago and this is the first docker image I ever run. Pretty embarrasing, I realize.

I pulled, just to be sure:
```
➜    docker pull klaemo/couchdb:2.0-dev
2.0-dev: Pulling from klaemo/couchdb

Digest: sha256:c9621d726740a5bcf13d7cb95763f1733bed597cf163bbe08eef863f5a6572dd
Status: Image is up to date for klaemo/couchdb:2.0-dev
```

I use MacOS X 10.11.2
Docker version 1.9.1, build a34a1d5

**Comment by klaemo** [comment] 2016-01-06 21:56
Haha so much for Docker's slogan "Build, ship and run anywhere"...
I have two virtual box docker machines on my Mac....on one it works, on the other one it doesn't:

<img width="1440" alt="docker-couchdb-shitshow" src="https://cloud.githubusercontent.com/assets/778624/12156001/a7d9ade4-b4c8-11e5-970a-4091941e393f.png">


:-( Different error than you. That doesn't make it any better. Docker can be such a shit show!

**Comment by peetersn** [comment] 2016-01-06 22:03
OK, so this bug report wasn't entirely unwarranted... I'm not so impressed so far, indeed :)
I'll try on Linux or go with the compile route...

Actually, now I have the same error as you (don't ask why):
```
[ * ] Setup environment ... ok
[ * ] Ensure CouchDB is built ... ok
[ * ] Prepare configuration files ... ok
[ * ] Start node node1 ... ok
[ * ] Start node node2 ... ok
[ * ] Start node node3 ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
[ * ] Check node at http://127.0.0.1:25984/ ... ok
[ * ] Check node at http://127.0.0.1:35984/ ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... ok
[ * ] Running cluster setup ... failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/src/couchdb/dev/run", line 535, in <module>
    main()
  File "/usr/src/couchdb/dev/run", line 73, in main
    startup(ctx)
  File "/usr/src/couchdb/dev/run", line 307, in startup
    cluster_setup(ctx)
  File "/usr/src/couchdb/dev/run", line 57, in wrapper
    res = func(*args, **kwargs)
  File "/usr/src/couchdb/dev/run", line 397, in cluster_setup
    add_node(lead_port, node_port, *ctx['admin'])
  File "/usr/src/couchdb/dev/run", line 429, in add_node
    'Content-Type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```
Should one other user have some ideas, feel free to post back in this issue.

**Comment by kxepal** [comment] 2016-01-06 22:16
Initial error happens but the same reason: connection refused. It just came from CouchDB, not Python script. The fun thing is that it fails after we ensure that all nodes are reachable. So something happens in-between passed checks and cluster setup.

Is it possible to extract dev/logs/* from container? Wonder what we'll find there.

**Comment by klaemo** [comment] 2016-01-06 22:20
@kxepal



[logs.zip](https://github.com/klaemo/docker-couchdb/files/80430/logs.zip)

**Comment by kxepal** [comment] 2016-01-06 22:30
@klaemo Thanks! Nothing interesting except haproxy failed to reach all the nodes. But that's irrelevant. The `system_memory_high_watermark` alarm tells that over 80% of memory is used. Could that be that it hits the borderline (dice roll guessing)?

**Comment by klaemo** [comment] 2016-01-06 22:33
Interesting. The VM where it's working has 2GB RAM, the other one has 1GB. I'll increase the memory and try again.

**Comment by klaemo** [comment] 2016-01-06 22:36
@kxepal @peetersn Tadaaa! Bumped the memory to 4GB for the VM and now it works. The Docker VM only gets 1GB by default. Does CouchDB need more than that?

**Comment by kxepal** [comment] 2016-01-06 22:39
@klaemo Definitely no. On my system I see that one node uses ~57MiB RAM (so ~180MiB for 3 nodes). Something else is super greedy there. Could you check what uses memory and how much?

**Comment by klaemo** [comment] 2016-01-06 22:50
I give up for today. I can get it to run only once. Then I have to restart the VM.

**Comment by kxepal** [comment] 2016-01-06 23:03
Things eventually starts to be better tomorrow (: Staying tuned on what you'll find!

**Comment by peetersn** [comment] 2016-01-10 11:05
Hi guys, sorry to be insisting, is there anything I can do on my side to test this on my machine?

**Comment by kerrr** [comment] 2016-01-15 12:06
I've had the same issue and upping the VMs RAM to 4GB resolved the issue.

**Comment by kxepal** [comment] 2016-01-15 12:08
That's not a healthy workaround, imho. Can anyone please check why? (I feel it's time to upgrade my system for docker).

**Comment by kerrr** [comment] 2016-01-15 13:30
Well that just got weird. I tried to go back and reproduce the issue and now it all works, even with the VM back in its original state. This may be difficult to track down :/

**Comment by klaemo** [comment] 2016-01-15 13:50
I'm seeing really inconsistent behavior as well. I have two VMs where it's working (on one of them it used to be broken) and a brand new one where it doesn't work. Unfortunately, I don't know enough about Virtual Box (or CouchDB for that matter) to debug this further. I'm willing to conduct any necessary experiments though, if anyone has ideas.

I don't think it has anything to do with the memory usage, because it works fine on a DigitalOcean VPS with 1GB RAM.

**Comment by mnewmedia** [comment] 2016-03-02 15:17
Same for me, first time installed docker.
loaded couchdb 1.6.1 -> started -> worked -> stopped.
loaded couchdb 2.0-dev -> started -> error 111

**Comment by kangu** [comment] 2016-03-08 21:02
Socket error 111 for me as well, tried to increase RAM to 4GB but nothing changed.

**Comment by ybian** [comment] 2016-03-14 23:55
I am having the same issue with the following command:

`docker run --rm -it klaemo/couchdb:2.0-dev`

I'm on OS X 10.11.3.

**Comment by mnewmedia** [comment] 2016-03-17 13:15
I really don't know docker. But i saw somewhere on docker hub, that a new build was done yesterday. Sow i tried it again and it worked today.

What i don't understand nothing changed on github, why does docker hub show new build made yesterday. And why is it working when nothing changed on this repo. 

Anyway it's working now, any others can confirm this, so we can close the issue?

**Comment by kerrr** [comment] 2016-03-17 13:39
I'm still seeing problems. Sometimes it works, sometimes it doesn't.

**Comment by antanst** [comment] 2016-03-18 08:28
I'm having the exact same issue. It's 100% reproducible on my machine (OSX El Capitan):

```
[ * ] Setup environment ... ok
[ * ] Ensure CouchDB is built ... ok
[ * ] Prepare configuration files ... ok
[ * ] Start node node1 ... ok
[ * ] Start node node2 ... ok
[ * ] Start node node3 ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
[ * ] Check node at http://127.0.0.1:25984/ ... ok
[ * ] Check node at http://127.0.0.1:35984/ ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... ok
[ * ] Running cluster setup ... failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/src/couchdb/dev/run", line 536, in <module>
    main()
  File "/usr/src/couchdb/dev/run", line 73, in main
    startup(ctx)
  File "/usr/src/couchdb/dev/run", line 308, in startup
    cluster_setup(ctx)
  File "/usr/src/couchdb/dev/run", line 57, in wrapper
    res = func(*args, **kwargs)
  File "/usr/src/couchdb/dev/run", line 398, in cluster_setup
    add_node(lead_port, node_port, *ctx['admin'])
  File "/usr/src/couchdb/dev/run", line 430, in add_node
    'Content-Type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

**Comment by klaemo** [comment] 2016-03-20 08:56
:( Does anyone have any idea what to do here?

**Comment by SrGrieves** [comment] 2016-05-03 15:15
I just experienced the same thing on a fresh Ubuntu 16.04 LTS VM.   Memory info at the end.

    $ sudo docker run -it -p 5984:5984 klaemo/couchdb:2.0-dev
    Unable to find image 'klaemo/couchdb:2.0-dev' locally
    2.0-dev: Pulling from klaemo/couchdb
    efd26ecc9548: Pull complete
    a3ed95caeb02: Pull complete
    5144ec4f10b4: Pull complete
    43b55ae05fba: Pull complete
    ef82412f1191: Pull complete
    Digest: sha256:edfa923d1c2a92a4aec9a00b8dedb5a7f926a371125c8c4e914c21cbb14bcb3f
    Status: Downloaded newer image for klaemo/couchdb:2.0-dev
    [ * ] Setup environment ... ok
    [ * ] Ensure CouchDB is built ... ok
    [ * ] Prepare configuration files ... ok
    [ * ] Start node node1 ... ok
    [ * ] Start node node2 ... ok
    [ * ] Start node node3 ... ok
    [ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
    [ * ] Check node at http://127.0.0.1:25984/ ... ok
    [ * ] Check node at http://127.0.0.1:35984/ ... ok
    [ * ] Check node at http://127.0.0.1:15984/ ... ok
    [ * ] Running cluster setup ... failed: [Errno 111] Connection refused
    Traceback (most recent call last):
      File "/usr/src/couchdb/dev/run", line 536, in <module>
        main()
      File "/usr/src/couchdb/dev/run", line 73, in main
        startup(ctx)
      File "/usr/src/couchdb/dev/run", line 308, in startup
        cluster_setup(ctx)
      File "/usr/src/couchdb/dev/run", line 57, in wrapper
        res = func(*args, **kwargs)
      File "/usr/src/couchdb/dev/run", line 398, in cluster_setup
        add_node(lead_port, node_port, *ctx['admin'])
      File "/usr/src/couchdb/dev/run", line 430, in add_node
        'Content-Type': 'application/json'})
      File "/usr/lib/python2.7/httplib.py", line 1001, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 812, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 793, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    socket.error: [Errno 111] Connection refused


    $ free -m
                  total        used        free      shared  buff/cache   available
    Mem:           3439         145        2138           4        1155        3233
    Swap:             0           0           0


    $ grep MemTotal /proc/meminfo
    MemTotal:        3521924 kB

**Comment by mbp** [comment] 2016-05-26 08:10
I have the same problem. Using Docker on Windows.

**Comment by mbp** [comment] 2016-05-30 13:41
I tried the same thing on an Amazon Linux EC2 Instance (m3.medium). Exactly same problem. :-(

**Comment by chrisfosterelli** [comment] 2016-05-30 23:31
Hey guys, we've been running into this in a variety of conditions, so I wanted to chime in some observations:

* 2/3 of our team members cannot get it to work on OSX with Virtualbox
* We seem to have 50/50 odds with getting it to work on Digital Ocean with Ubuntu
* It is sometimes inconsistent. Some machines that it works on will fail every now and then and some machines it doesn't work on with succeed every now and then.
* We've noticed that starting it with `-n 1` seems to have much less success than starting it with `-n 3`.

Is this potentially a race condition somewhere?

**Comment by klaemo** [comment] 2016-08-17 20:21
Anyone seeing this with the 2.0-rc images?

**Comment by chrisfosterelli** [comment] 2016-08-17 20:33
@klaemo Not sure about 2.0-rc, but we've been running 2.0-single for a while and not seen this anymore.

**Comment by garrensmith** [comment] 2016-11-14 07:52
I'm closing this since it seems resolved.

**Closed by garrensmith** 2016-11-14 07:52 UTC
Labels: needs help
